### ISSUE TITLE
OTA Update broken

### ISSUE THREAD

**Issue by Woi** [microg/microg.org#16]
I recognises that this weeks OTA update didn't arrived automatically. Triggering a manual search gives me the message  "Search for Updates failed. [...]". So I dug a bit deeper and fired up `adb` to check the logfiles:
```
04-22 18:59:31.507 19301 19301 D UpdatesActivity: Checking https://lineage.microg.org/api
04-22 18:59:31.749 19301 19301 D UpdatesActivity: List downloaded
04-22 18:59:31.749 19301 19301 D UpdatesActivity: Adding remote updates
04-22 18:59:31.766 19301 19301 E UpdatesActivity: Could not read json
04-22 18:59:31.766 19301 19301 E UpdatesActivity: org.json.JSONException: Value WOHOOO of type java.lang.String cannot be converted to JSONObject
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.json.JSON.typeMismatch(JSON.java:111)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.json.JSONObject.<init>(JSONObject.java:160)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.json.JSONObject.<init>(JSONObject.java:173)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.misc.Utils.parseJson(Utils.java:125)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.UpdatesActivity.loadUpdatesList(UpdatesActivity.java:244)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.UpdatesActivity.processNewJson(UpdatesActivity.java:300)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.UpdatesActivity.-wrap2(UpdatesActivity.java)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.UpdatesActivity$4.-org_lineageos_updater_UpdatesActivity$4_lambda$3(UpdatesActivity.java:345)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at org.lineageos.updater.UpdatesActivity$4$-void_onSuccess_java_io_File_destination_LambdaImpl0.run(UpdatesActivity.java)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at android.os.Handler.handleCallback(Handler.java:751)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at android.os.Looper.loop(Looper.java:154)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at android.app.ActivityThread.main(ActivityThread.java:6186)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at java.lang.reflect.Method.invoke(Native Method)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-22 18:59:31.766 19301 19301 E UpdatesActivity:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
Is this an issue with the microg.org API or a bug introduces with last weeks upstream patches (search for updater on https://www.cmxlog.com/14.1/)?

My device is an Samsung Galaxy S3 i9300, running `14.1-20180412-i9300`

**Comment by ArchangeGabriel** [comment]
This is known: https://github.com/lineageos4microg/docker-lineage-cicd/issues/12.

**Comment by Woi** [comment]
Thanks for this lightning fast reply.
